name: Node.js Matrix Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            npm test -- --maxWorkers=1
          else
            npm test -- --passWithNoTests

